services:
  nusearch:
    image: public.ecr.aws/dissco/col-nusearch-service:latest
    ports:
      - 8080:8080
    environment:
        - indexing.col-password=${COL_PASSWORD}
        - indexing.col-username=${COL_USERNAME}
        - indexing.col-dataset=2014
        - indexing.index-location=/index-files/index
        - indexing.delete-index=true
        - indexing.index-at-startup=true
        - indexing.temp-coldp-location=/index-files/col-temp.zip
    volumes:
      - /tmp:/index-files
